modules
  name: Application

  description: |
  
  
constructors
  constructor:
    description: | 
      @api public
      @param {<type>} options - 
  
    examples:
      -
        name: 
        example: |
        
      
properties
  options: |
    <description>
  
    @type {<type>}
    
  _initCallbacks: |
    <description>
  
    @type {<type>}
    
  submodules: |
    <description>
  
    @type {<type>}
    
  _regionManager: |
    <description>
  
    @type {<type>}
    
  name: |
    <description>
  
    @type {<type>}
    
  channelName: |
    <description>
  
    @type {<type>}
    
  channel: |
    <description>
  
    @type {<type>}
    
  vent: |
    <description>
  
    @type {<type>}
    
  commands: |
    <description>
  
    @type {<type>}
    
  reqres: |
    <description>
  
    @type {<type>}
    
functions
  initialize:
    description: | 
      @api public
  
    examples:
      -
        name: 
        example: |
        
      
  execute:
    description: | 
      @api public
  
    examples:
      -
        name: 
        example: |
        
      
  request:
    description: | 
      @api public
      @returns {<type>} -
  
    examples:
      -
        name: 
        example: |
        
      
  addInitializer:
    description: | 
      @api public
      @param {<type>} initializer - <description>
  
    examples:
      -
        name: 
        example: |
        
      
  start:
    description: | 
      @api public
      @param {<type>} options - <description>
  
    examples:
      -
        name: 
        example: |
        
      
  addRegions:
    description: | 
      @api public
      @param {<type>} regions - <description>
      @returns {<type>} -
  
    examples:
      -
        name: 
        example: |
        
      
  emptyRegions:
    description: | 
      @api public
      @returns {<type>} -
  
    examples:
      -
        name: 
        example: |
        
      
  removeRegion:
    description: | 
      @api public
      @param {<type>} region - <description>
      @returns {<type>} -
  
    examples:
      -
        name: 
        example: |
        
      
  getRegion:
    description: | 
      @api public
      @param {<type>} region - <description>
      @returns {<type>} -
  
    examples:
      -
        name: 
        example: |
        
      
  getRegions:
    description: | 
      @api public
      @returns {<type>} -
  
    examples:
      -
        name: 
        example: |
        
      
  module:
    description: | 
      @api public
      @param {<type>} moduleNames - <description>
      @param {<type>} moduleDefinition - <description>
      @returns {<type>} -
  
    examples:
      -
        name: 
        example: |
        
      
  getRegionManager:
    description: | 
      @api public
      @returns {<type>} -
  
    examples:
      -
        name: 
        example: |
        
      
  _initializeRegions:
    description: | 
      @api private
      @param {<type>} options - <description>
      @returns {<type>} -
  
    examples:
      -
        name: 
        example: |
        
      
  _initRegionManager:
    description: | 
      @api private
  
    examples:
      -
        name: 
        example: |
        
      
  _initChannel:
    description: | 
      @api private
  
    examples:
      -
        name: 
        example: |
        
      
events
  name: before:start

  description: | 

  example: | 
      
  name: start

  description: | 

  example: | 
      
