name: application.js

description: |
  <module description>
  
constructor:
  description: | 
    @api public
    @param {<type>} options - 
  
  examples:
    -
      name:
      example: |
      
initialize:
  description: | 
    @api public
  
  examples:
    -
      name:
      example: |
      
execute:
  description: | 
    @api public
  
  examples:
    -
      name:
      example: |
      
request:
  description: | 
    @api public
    @returns {type} -
  
  examples:
    -
      name:
      example: |
      
addInitializer:
  description: | 
    @api public
    @param {<type>} initializer - 
  
  examples:
    -
      name:
      example: |
      
start:
  description: | 
    @api public
    @param {<type>} options - 
  
  examples:
    -
      name:
      example: |
      
name: before:start

description: |

example: |
      
name: start

description: |

example: |
      
addRegions:
  description: | 
    @api public
    @param {<type>} regions - 
    @returns {type} -
  
  examples:
    -
      name:
      example: |
      
emptyRegions:
  description: | 
    @api public
    @returns {type} -
  
  examples:
    -
      name:
      example: |
      
removeRegion:
  description: | 
    @api public
    @param {<type>} region - 
    @returns {type} -
  
  examples:
    -
      name:
      example: |
      
getRegion:
  description: | 
    @api public
    @param {<type>} region - 
    @returns {type} -
  
  examples:
    -
      name:
      example: |
      
getRegions:
  description: | 
    @api public
    @returns {type} -
  
  examples:
    -
      name:
      example: |
      
module:
  description: | 
    @api public
    @param {<type>} moduleNames - 
    @param {<type>} moduleDefinition - 
    @returns {type} -
  
  examples:
    -
      name:
      example: |
      
getRegionManager:
  description: | 
    @api public
    @returns {type} -
  
  examples:
    -
      name:
      example: |
      
_initializeRegions:
  description: | 
    @api private
    @param {<type>} options - 
    @returns {type} -
  
  examples:
    -
      name:
      example: |
      
_initRegionManager:
  description: | 
    @api private
  
  examples:
    -
      name:
      example: |
      
_initChannel:
  description: | 
    @api private
  
  examples:
    -
      name:
      example: |
      
