name: marionette.application.js

description: |
  <module description>
  
class: Application

description: |
  <class description>
  
initialize:
  description: | 
  
  examples:
    -
      name:
      example: |
      
execute:
  description: | 
  
  examples:
    -
      name:
      example: |
      
request:
  description: | 
    @returns {type} - <returns description>
  
  examples:
    -
      name:
      example: |
      
addInitializer:
  description: | 
    @param {type} initializer - <param description> 
  
  examples:
    -
      name:
      example: |
      
start:
  description: | 
    @param {type} options - <param description> 
  
  examples:
    -
      name:
      example: |
      
addRegions:
  description: | 
    @param {type} regions - <param description> 
    @returns {type} - <returns description>
  
  examples:
    -
      name:
      example: |
      
emptyRegions:
  description: | 
    @returns {type} - <returns description>
  
  examples:
    -
      name:
      example: |
      
removeRegion:
  description: | 
    @param {type} region - <param description> 
    @returns {type} - <returns description>
  
  examples:
    -
      name:
      example: |
      
getRegion:
  description: | 
    @param {type} region - <param description> 
    @returns {type} - <returns description>
  
  examples:
    -
      name:
      example: |
      
getRegions:
  description: | 
    @returns {type} - <returns description>
  
  examples:
    -
      name:
      example: |
      
module:
  description: | 
    @param {type} moduleNames - <param description> 
    @param {type} moduleDefinition - <param description> 
    @returns {type} - <returns description>
  
  examples:
    -
      name:
      example: |
      
getRegionManager:
  description: | 
    @returns {type} - <returns description>
  
  examples:
    -
      name:
      example: |
      
_initializeRegions:
  description: | 
    @param {type} options - <param description> 
    @returns {type} - <returns description>
  
  examples:
    -
      name:
      example: |
      
_initRegionManager:
  description: | 
  
  examples:
    -
      name:
      example: |
      
name: | before:add:region
  
  description: |
    
    example: |
      
name: | add:region
  
  description: |
    
    example: |
      
name: | before:remove:region
  
  description: |
    
    example: |
      
name: | remove:region
  
  description: |
    
    example: |
      
_initChannel:
  description: | 
  
  examples:
    -
      name:
      example: |
      
